# Site settings
title: Fariq Site
description: "Fariqussalam Personal Site and Blog"
url: "https://fariqussalam.github.io"
author:
  name: "Fariqussalam Malik"
  email: "fariqussalam@gmail.com"
  url: "https://fariqussalam.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: blog/page:num/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
plugins: [jekyll-paginate]

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
